//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDViajero.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int IdReserva { get; set; }
        public int IdViajero { get; set; }
        public int IdDestino { get; set; }
        public int PlazasReserva { get; set; }
        public string LugarOrigen { get; set; }
        public Nullable<System.DateTime> FechaReserva { get; set; }
    
        public virtual Destinos Destinos { get; set; }
        public virtual Viajeros Viajeros { get; set; }
    }
}
